const actions = {
  CLEAR_CLIENT_VIEW: 'CLEAR_CLIENT_VIEW',
  CLEAR_POPUP_CONTENT: 'CLEAR_POPUP_CONTENT',
  SET_PROFILE_VIEW: 'SET_PROFILE_VIEW',
  SET_CLIENT_VIEW: 'SET_CLIENT_VIEW',
  SET_POPUP_CONTENT: 'SET_POPUP_CONTENT',
  TOGGLE_POPUP: 'TOGGLE_POPUP',
}
export default actions;